# Generated by Django 3.0.8 on 2020-11-19 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0002_testtabelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testkunde1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
