# Generated by Django 3.0.8 on 2020-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0003_testkunde1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testkunde1',
        ),
        migrations.AddField(
            model_name='testkunde',
            name='nname',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='testkunde',
            name='tel',
            field=models.CharField(default='0664', max_length=250),
        ),
        migrations.AddField(
            model_name='testkunde',
            name='vname',
            field=models.CharField(default='vname', max_length=250),
        ),
    ]
