# Generated by Django 3.0.8 on 2020-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0005_testkunde_ausw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testkunde',
            name='ausw',
            field=models.CharField(choices=[('Ausw1', 'Ausw2'), ('Ausw2', 'ausw2'), ('Ausw3', 'ausw3')], default='Ausw1', max_length=10),
        ),
    ]
