# Generated by Django 3.0.8 on 2020-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0006_auto_20201119_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testtabelle',
        ),
        migrations.AddField(
            model_name='testkunde',
            name='zahl1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testkunde',
            name='zahl2',
            field=models.IntegerField(default=2),
        ),
    ]
