# Generated by Django 3.0.8 on 2020-12-03 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('angebot', '0012_auto_20201203_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1_Angebot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesamtsumme', models.IntegerField(default='0')),
                ('anschlussS', models.IntegerField(default='0')),
                ('anschlussM', models.IntegerField(default='0')),
                ('anschlussL', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Test1_Baustoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baustoffart', models.CharField(default='', max_length=100)),
                ('baustoffwert', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Test1_Bauweise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bauweiseart', models.CharField(default='', max_length=100)),
                ('bauweisebezeichnung', models.CharField(default='', max_length=100)),
                ('bauweisewert', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Test1_Heizkoerper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(default='', max_length=100)),
                ('preis', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Test1_Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektkunde', models.CharField(default='', max_length=250)),
                ('plz', models.CharField(default='', max_length=4)),
                ('ort', models.CharField(default='', max_length=30)),
                ('telefonnr', models.CharField(default='', max_length=15)),
                ('mail', models.EmailField(default='', max_length=100)),
                ('strasse', models.CharField(default='', max_length=100)),
                ('heiztage', models.IntegerField(default=0)),
                ('raumtemp', models.IntegerField(default=22)),
                ('stromkosten', models.CharField(default='', max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test1_Objekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dickeaussenwand', models.IntegerField(default='0')),
                ('dickedaemmung', models.IntegerField(default='0')),
                ('uwert', models.IntegerField(default='0')),
                ('fensterqualitaet', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('baustoffid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='angebot.Test1_Baustoff')),
                ('bauweiseid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='angebot.Test1_Bauweise')),
            ],
        ),
        migrations.CreateModel(
            name='Test1_Raum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('hoehe', models.IntegerField(default='0')),
                ('flaeche', models.IntegerField(default='0')),
                ('anzfenster', models.IntegerField(default='0')),
                ('anzaussenfenster', models.IntegerField(default='0')),
                ('alternative', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('s', models.IntegerField(default='0')),
                ('m', models.IntegerField(default='0')),
                ('l', models.IntegerField(default='0')),
                ('es980', models.IntegerField(default='0')),
                ('es981', models.IntegerField(default='0')),
                ('es982', models.IntegerField(default='0')),
                ('es800', models.IntegerField(default='0')),
                ('es810', models.IntegerField(default='0')),
                ('es820', models.IntegerField(default='0')),
                ('es700', models.IntegerField(default='0')),
                ('angebotid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angebot.Test1_Angebot')),
            ],
        ),
        migrations.CreateModel(
            name='Test1_Steuerung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('preis', models.IntegerField(default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='test_angebot',
            name='kundenid',
        ),
        migrations.RemoveField(
            model_name='test_angebot',
            name='ojektid',
        ),
        migrations.DeleteModel(
            name='Test_Heizkoerper',
        ),
        migrations.RemoveField(
            model_name='test_kunde',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='baustoffid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='bauweiseid',
        ),
        migrations.RemoveField(
            model_name='test_raum',
            name='angebotid',
        ),
        migrations.DeleteModel(
            name='Test_Steuerung',
        ),
        migrations.DeleteModel(
            name='Test_Angebot',
        ),
        migrations.DeleteModel(
            name='Test_Baustoff',
        ),
        migrations.DeleteModel(
            name='Test_Bauweise',
        ),
        migrations.DeleteModel(
            name='Test_Kunde',
        ),
        migrations.DeleteModel(
            name='Test_Objekt',
        ),
        migrations.DeleteModel(
            name='Test_Raum',
        ),
        migrations.AddField(
            model_name='test1_angebot',
            name='kundenid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angebot.Test1_Kunde'),
        ),
        migrations.AddField(
            model_name='test1_angebot',
            name='ojektid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='angebot.Test1_Objekt'),
        ),
    ]
