# Generated by Django 3.0.8 on 2020-12-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0013_auto_20201203_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1_angebot',
            name='ojektid',
        ),
    ]
