# Generated by Django 3.0.8 on 2020-12-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0014_remove_test1_angebot_ojektid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1_angebot',
            name='kundenid',
        ),
        migrations.DeleteModel(
            name='Test1_Heizkoerper',
        ),
        migrations.RemoveField(
            model_name='test1_kunde',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='test1_objekt',
            name='baustoffid',
        ),
        migrations.RemoveField(
            model_name='test1_objekt',
            name='bauweiseid',
        ),
        migrations.RemoveField(
            model_name='test1_raum',
            name='angebotid',
        ),
        migrations.DeleteModel(
            name='Test1_Steuerung',
        ),
        migrations.DeleteModel(
            name='Test1_Angebot',
        ),
        migrations.DeleteModel(
            name='Test1_Baustoff',
        ),
        migrations.DeleteModel(
            name='Test1_Bauweise',
        ),
        migrations.DeleteModel(
            name='Test1_Kunde',
        ),
        migrations.DeleteModel(
            name='Test1_Objekt',
        ),
        migrations.DeleteModel(
            name='Test1_Raum',
        ),
    ]
