# Generated by Django 3.0.8 on 2020-12-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0017_test_angebot_ojektid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_angebot',
            name='anschlussM',
        ),
        migrations.RemoveField(
            model_name='test_angebot',
            name='anschlussS',
        ),
        migrations.RemoveField(
            model_name='test_angebot',
            name='gesamtsumme',
        ),
        migrations.RemoveField(
            model_name='test_angebot',
            name='kundenid',
        ),
        migrations.RemoveField(
            model_name='test_angebot',
            name='ojektid',
        ),
    ]
