# Generated by Django 3.0.8 on 2020-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0018_auto_20201204_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_angebot',
            name='anschlussM',
            field=models.IntegerField(default='0'),
        ),
    ]
