# Generated by Django 3.0.8 on 2020-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0022_test_angebot_ojektid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_angebot',
            name='status',
            field=models.BooleanField(choices=[(True, 'offen'), (False, 'abgeschlossen')], default='True'),
        ),
    ]
