# Generated by Django 3.0.8 on 2020-12-09 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0023_test_angebot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_kunde',
            old_name='projektkunde',
            new_name='kunde',
        ),
        migrations.AddField(
            model_name='test_angebot',
            name='datum_erstellt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test_angebot',
            name='titel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
