# Generated by Django 3.0.8 on 2020-12-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0024_auto_20201209_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_objekt',
            name='bezeichnung',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_angebot',
            name='status',
            field=models.BooleanField(choices=[(True, 'offen'), (False, 'abgeschlossen')], default=True),
        ),
        migrations.AlterField(
            model_name='test_objekt',
            name='fensterqualitaet',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='test_raum',
            name='alternative',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
