# Generated by Django 3.0.8 on 2020-12-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0025_auto_20201210_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_raum',
            name='angebotid',
        ),
        migrations.AddField(
            model_name='test_raum',
            name='objektid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Objekt'),
            preserve_default=False,
        ),
    ]
