# Generated by Django 3.0.8 on 2020-12-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0027_remove_test_angebot_ojektid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_objekt',
            name='angebotid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Angebot'),
            preserve_default=False,
        ),
    ]
