# Generated by Django 3.0.8 on 2020-12-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0028_test_objekt_angebotid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_angebot',
            name='anschlussL',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='test_angebot',
            name='anschlussM',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='test_angebot',
            name='anschlussS',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='test_angebot',
            name='gesamtsumme',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='test_angebot',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_baustoff',
            name='baustoffart',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_bauweise',
            name='bauweiseart',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_bauweise',
            name='bauweisebezeichnung',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_heizkoerper',
            name='bezeichnung',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='kunde',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='ort',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='plz',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='strasse',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='stromkosten',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='telefonnr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='test_objekt',
            name='bezeichnung',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_objekt',
            name='dickeaussenwand',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='test_raum',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_steuerung',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
