# Generated by Django 3.0.8 on 2020-12-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0030_auto_20201211_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_baustoff',
            old_name='baustoffart',
            new_name='art',
        ),
        migrations.RenameField(
            model_name='test_baustoff',
            old_name='baustoffwert',
            new_name='wert',
        ),
        migrations.RenameField(
            model_name='test_bauweise',
            old_name='bauweiseart',
            new_name='art',
        ),
        migrations.RenameField(
            model_name='test_bauweise',
            old_name='bauweisebezeichnung',
            new_name='bezeichnung',
        ),
        migrations.RenameField(
            model_name='test_bauweise',
            old_name='bauweisewert',
            new_name='wert',
        ),
        migrations.AddField(
            model_name='test_bauweise',
            name='energiekennzahl',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
