# Generated by Django 3.0.8 on 2020-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0031_auto_20201212_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_angebot',
            name='kundenid',
        ),
        migrations.DeleteModel(
            name='Test_Heizkoerper',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='angebotid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='baustoffid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='bauweiseid',
        ),
        migrations.RemoveField(
            model_name='test_raum',
            name='objektid',
        ),
        migrations.DeleteModel(
            name='Test_Steuerung',
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='kunde',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='ort',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='plz',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='raumtemp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='strasse',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='stromkosten',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='telefonnr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Test_Angebot',
        ),
        migrations.DeleteModel(
            name='Test_Baustoff',
        ),
        migrations.DeleteModel(
            name='Test_Bauweise',
        ),
        migrations.DeleteModel(
            name='Test_Objekt',
        ),
        migrations.DeleteModel(
            name='Test_Raum',
        ),
    ]
