# Generated by Django 3.0.8 on 2020-12-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0033_test_angebot_test_baustoff_test_bauweise_test_heizkoerper_test_objekt_test_raum_test_steuerung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_objekt',
            name='angebotid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Angebot'),
        ),
    ]
