# Generated by Django 3.0.8 on 2020-12-15 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0034_auto_20201215_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_objekt',
            name='angebotid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Angebot'),
        ),
    ]
