# Generated by Django 3.0.8 on 2020-12-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firma',
            field=models.CharField(default='Firma:', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.EmailField(default='Mail:', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='ort',
            field=models.CharField(default='Ort:', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='plz',
            field=models.CharField(default='PLZ:', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='strasse',
            field=models.CharField(default='Straße:', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefonnr',
            field=models.CharField(default='Tel:', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='prof1ile_pics'),
        ),
    ]
