# Generated by Django 3.0.8 on 2020-12-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0031_auto_20201212_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_angebot',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_baustoff',
            name='art',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_bauweise',
            name='art',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_bauweise',
            name='bezeichnung',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_bauweise',
            name='energiekennzahl',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='test_heizkoerper',
            name='bezeichnung',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='kunde',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='ort',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='plz',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='raumtemp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='strasse',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='stromkosten',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='test_kunde',
            name='telefonnr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='test_objekt',
            name='baustoffid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Baustoff'),
        ),
        migrations.AlterField(
            model_name='test_objekt',
            name='bauweiseid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Bauweise'),
        ),
        migrations.AlterField(
            model_name='test_objekt',
            name='bezeichnung',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_raum',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_steuerung',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
