# Generated by Django 3.0.8 on 2020-12-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0033_auto_20201214_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_baustoff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='baustoffid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='bauweiseid',
        ),
        migrations.AddField(
            model_name='test_objekt',
            name='baustoffart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Baustoff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_objekt',
            name='bauweiseart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Bauweise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_baustoff',
            name='art',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
