# Generated by Django 3.0.8 on 2020-12-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0035_auto_20201214_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_objekt',
            name='baustoffart',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='bauweiseart',
        ),
        migrations.AddField(
            model_name='test_baustoff',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_bauweise',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_objekt',
            name='baustoffid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Baustoff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_objekt',
            name='bauweiseid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Bauweise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_baustoff',
            name='art',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test_bauweise',
            name='art',
            field=models.CharField(max_length=100),
        ),
    ]
