# Generated by Django 3.0.8 on 2020-12-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0036_auto_20201214_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_objekt',
            name='baustoffid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='bauweiseid',
        ),
    ]
