# Generated by Django 3.0.8 on 2020-12-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0038_auto_20201214_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_raum',
            name='objektid',
        ),
        migrations.DeleteModel(
            name='Test_Objekt',
        ),
    ]
