# Generated by Django 3.0.8 on 2020-12-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0040_test_objekt'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_raum',
            name='objektid',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Objekt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_objekt',
            name='angebotid',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='angebot.Test_Angebot'),
            preserve_default=False,
        ),
    ]
