# Generated by Django 3.0.8 on 2020-12-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angebot', '0041_auto_20201214_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_angebot',
            name='kundenid',
        ),
        migrations.DeleteModel(
            name='Test_Heizkoerper',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='angebotid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='baustoffid',
        ),
        migrations.RemoveField(
            model_name='test_objekt',
            name='bauweiseid',
        ),
        migrations.RemoveField(
            model_name='test_raum',
            name='objektid',
        ),
        migrations.DeleteModel(
            name='Test_Steuerung',
        ),
        migrations.DeleteModel(
            name='Test_Angebot',
        ),
        migrations.DeleteModel(
            name='Test_Baustoff',
        ),
        migrations.DeleteModel(
            name='Test_Bauweise',
        ),
        migrations.DeleteModel(
            name='Test_Objekt',
        ),
        migrations.DeleteModel(
            name='Test_Raum',
        ),
    ]
